/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TransportistaRouteImport } from './routes/transportista'
import { Route as AuthRegistroRouteImport } from './routes/auth/registro'
import { Route as MarketplaceCarritoRouteImport } from './routes/marketplace/carrito'
import { Route as MarketplaceMinisuperRouteImport } from './routes/marketplace/minisuper'
import { Route as ProductorPublishRouteImport } from './routes/productor/publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportistaRoute = TransportistaRouteImport.update({
  id: '/transportista',
  path: '/transportista',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/auth/registro',
  path: '/auth/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCarritoRoute = MarketplaceCarritoRouteImport.update({
  id: '/marketplace/carrito',
  path: '/marketplace/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceMinisuperRoute = MarketplaceMinisuperRouteImport.update({
  id: '/marketplace/minisuper',
  path: '/marketplace/minisuper',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorPublishRoute = ProductorPublishRouteImport.update({
  id: '/productor/publish',
  path: '/productor/publish',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/transportista': typeof TransportistaRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/marketplace/carrito': typeof MarketplaceCarritoRoute
  '/marketplace/minisuper': typeof MarketplaceMinisuperRoute
  '/productor/publish': typeof ProductorPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/transportista': typeof TransportistaRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/marketplace/carrito': typeof MarketplaceCarritoRoute
  '/marketplace/minisuper': typeof MarketplaceMinisuperRoute
  '/productor/publish': typeof ProductorPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/transportista': typeof TransportistaRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/marketplace/carrito': typeof MarketplaceCarritoRoute
  '/marketplace/minisuper': typeof MarketplaceMinisuperRoute
  '/productor/publish': typeof ProductorPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/transportista'
    | '/auth/registro'
    | '/marketplace/carrito'
    | '/marketplace/minisuper'
    | '/productor/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/transportista'
    | '/auth/registro'
    | '/marketplace/carrito'
    | '/marketplace/minisuper'
    | '/productor/publish'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/transportista'
    | '/auth/registro'
    | '/marketplace/carrito'
    | '/marketplace/minisuper'
    | '/productor/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  TransportistaRoute: typeof TransportistaRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
  MarketplaceCarritoRoute: typeof MarketplaceCarritoRoute
  MarketplaceMinisuperRoute: typeof MarketplaceMinisuperRoute
  ProductorPublishRoute: typeof ProductorPublishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportista': {
      id: '/transportista'
      path: '/transportista'
      fullPath: '/transportista'
      preLoaderRoute: typeof TransportistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registro': {
      id: '/auth/registro'
      path: '/auth/registro'
      fullPath: '/auth/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/carrito': {
      id: '/marketplace/carrito'
      path: '/marketplace/carrito'
      fullPath: '/marketplace/carrito'
      preLoaderRoute: typeof MarketplaceCarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/minisuper': {
      id: '/marketplace/minisuper'
      path: '/marketplace/minisuper'
      fullPath: '/marketplace/minisuper'
      preLoaderRoute: typeof MarketplaceMinisuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/publish': {
      id: '/productor/publish'
      path: '/productor/publish'
      fullPath: '/productor/publish'
      preLoaderRoute: typeof ProductorPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  TransportistaRoute: TransportistaRoute,
  AuthRegistroRoute: AuthRegistroRoute,
  MarketplaceCarritoRoute: MarketplaceCarritoRoute,
  MarketplaceMinisuperRoute: MarketplaceMinisuperRoute,
  ProductorPublishRoute: ProductorPublishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
